import connectDB from '../lib/mongodb';
import Property from '../models/Property';

const properties = [
  {
    title: 'Luxury Villa in Palm Jumeirah',
    description: 'Experience luxury living in this stunning villa with private beach access',
    images: ['/images/properties/dubai1.jpg', '/images/properties/dubai1-2.jpg', '/images/properties/dubai1-3.jpg'],
    price: 2500,
    location: 'Palm Jumeirah, Dubai',
    propertyType: 'villa',
    bedrooms: 5,
    bathrooms: 6,
    guests: 10,
    amenities: ['Private Pool', 'Beach Access', 'Garden', 'BBQ Area', 'Smart Home', 'Gym'],
    whatsapp: '+971501234567',
    instantBook: true,
    superhost: true,
    rating: 4.9,
    reviewCount: 124,
    coordinates: {
      latitude: 25.1124,
      longitude: 55.1390
    },
    rules: {
      smoking: false,
      pets: true,
      parties: false,
      minimumStay: 2
    },
    accessibility: ['Elevator', 'Wide doorways', 'Ground floor access'],
    languages: ['English', 'Arabic'],
    cancellationPolicy: 'moderate',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: true,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Modern Apartment in Downtown',
    description: 'Stylish apartment with breathtaking views of Burj Khalifa',
    images: ['/images/properties/dubai2.jpg', '/images/properties/dubai2-2.jpg', '/images/properties/dubai2-3.jpg'],
    price: 1200,
    location: 'Downtown Dubai',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2.5,
    guests: 4,
    amenities: ['Burj Khalifa View', 'Pool', 'Gym', 'Parking', '24/7 Security'],
    whatsapp: '+971501234568',
    instantBook: true,
    superhost: false,
    rating: 4.7,
    reviewCount: 89,
    coordinates: {
      latitude: 25.1972,
      longitude: 55.2744
    },
    rules: {
      smoking: false,
      pets: false,
      parties: false,
      minimumStay: 3
    },
    accessibility: ['Elevator'],
    languages: ['English', 'Arabic', 'Hindi'],
    cancellationPolicy: 'flexible',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Beachfront Villa in JBR',
    description: 'Beautiful beachfront villa with stunning sea views',
    images: ['/images/properties/dubai3.jpg', '/images/properties/dubai3-2.jpg', '/images/properties/dubai3-3.jpg'],
    price: 1800,
    location: 'JBR, Dubai',
    propertyType: 'villa',
    bedrooms: 4,
    bathrooms: 4,
    guests: 8,
    amenities: ['Beach Access', 'Private Pool', 'Terrace', 'BBQ Area', 'Maid Room'],
    whatsapp: '+971501234569',
    instantBook: false,
    superhost: true,
    rating: 4.8,
    reviewCount: 156,
    coordinates: {
      latitude: 25.0799,
      longitude: 55.1335
    },
    rules: {
      smoking: false,
      pets: true,
      parties: true,
      minimumStay: 2
    },
    accessibility: ['Ground floor access', 'Wide doorways'],
    languages: ['English', 'Arabic', 'Russian'],
    cancellationPolicy: 'strict',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Penthouse in Dubai Marina',
    description: 'Luxurious penthouse with panoramic marina views',
    images: ['/images/properties/dubai4.jpg', '/images/properties/dubai4-2.jpg', '/images/properties/dubai4-3.jpg'],
    price: 2000,
    location: 'Dubai Marina',
    propertyType: 'penthouse',
    bedrooms: 3,
    bathrooms: 3.5,
    guests: 6,
    amenities: ['Marina View', 'Private Pool', 'Jacuzzi', 'Home Theater', 'Private Elevator'],
    whatsapp: '+971501234570',
    instantBook: true,
    superhost: true,
    rating: 4.9,
    reviewCount: 201,
    coordinates: {
      latitude: 25.0817,
      longitude: 55.1403
    },
    rules: {
      smoking: false,
      pets: false,
      parties: false,
      minimumStay: 3
    },
    accessibility: ['Elevator', 'Wide doorways'],
    languages: ['English', 'Arabic', 'Chinese'],
    cancellationPolicy: 'strict',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: true,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Traditional Villa in Al Barsha',
    description: 'Spacious family villa with modern amenities',
    images: ['/images/properties/dubai5.jpg', '/images/properties/dubai5-2.jpg', '/images/properties/dubai5-3.jpg'],
    price: 1500,
    location: 'Al Barsha, Dubai',
    propertyType: 'villa',
    bedrooms: 4,
    bathrooms: 4,
    guests: 8,
    amenities: ['Private Pool', 'Garden', 'Majlis', 'Parking', 'Maid Room'],
    whatsapp: '+971501234571',
    instantBook: false,
    superhost: false,
    rating: 4.6,
    reviewCount: 78,
    coordinates: {
      latitude: 25.1107,
      longitude: 55.2038
    },
    rules: {
      smoking: false,
      pets: true,
      parties: false,
      minimumStay: 4
    },
    accessibility: ['Ground floor access'],
    languages: ['English', 'Arabic', 'Urdu'],
    cancellationPolicy: 'moderate',
    selfCheckIn: false,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: false,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Luxury Apartment in Business Bay',
    description: 'Modern apartment with stunning views of the Dubai Canal',
    images: ['/images/properties/dubai1.jpg', '/images/properties/dubai1-2.jpg'],
    price: 1600,
    location: 'Business Bay, Dubai',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    amenities: ['Canal View', 'Gym', 'Pool', 'Parking', 'Business Center'],
    whatsapp: '+971501234572',
    instantBook: true,
    superhost: false,
    rating: 4.7,
    reviewCount: 92,
    coordinates: {
      latitude: 25.1872,
      longitude: 55.2744
    },
    rules: {
      smoking: false,
      pets: false,
      parties: false,
      minimumStay: 2
    },
    accessibility: ['Elevator'],
    languages: ['English', 'Arabic'],
    cancellationPolicy: 'moderate',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Cozy Studio in Dubai Silicon Oasis',
    description: 'Perfect for digital nomads and tech professionals',
    images: ['/images/properties/dubai2.jpg', '/images/properties/dubai2-2.jpg'],
    price: 800,
    location: 'Dubai Silicon Oasis',
    propertyType: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: ['High-speed Internet', 'Work Desk', 'Smart TV', 'Gym Access'],
    whatsapp: '+971501234573',
    instantBook: true,
    superhost: false,
    rating: 4.5,
    reviewCount: 45,
    coordinates: {
      latitude: 25.1179,
      longitude: 55.3789
    },
    rules: {
      smoking: false,
      pets: false,
      parties: false,
      minimumStay: 1
    },
    accessibility: ['Elevator'],
    languages: ['English', 'Hindi'],
    cancellationPolicy: 'flexible',
    selfCheckIn: true,
    parking: true,
    pool: false,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: false,
    workspace: true,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Waterfront Villa in Palm Jebel Ali',
    description: 'Exclusive beachfront villa with private beach access',
    images: ['/images/properties/dubai3.jpg', '/images/properties/dubai3-2.jpg'],
    price: 3500,
    location: 'Palm Jebel Ali, Dubai',
    propertyType: 'villa',
    bedrooms: 6,
    bathrooms: 7,
    guests: 12,
    amenities: ['Private Beach', 'Infinity Pool', 'Home Theater', 'Private Chef'],
    whatsapp: '+971501234574',
    instantBook: false,
    superhost: true,
    rating: 4.9,
    reviewCount: 28,
    coordinates: {
      latitude: 25.0084,
      longitude: 55.1183
    },
    rules: {
      smoking: false,
      pets: true,
      parties: true,
      minimumStay: 3
    },
    accessibility: ['Ground floor access', 'Wide doorways'],
    languages: ['English', 'Arabic', 'Russian'],
    cancellationPolicy: 'strict',
    selfCheckIn: false,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Designer Loft in DIFC',
    description: 'Stylish loft apartment in Dubai\'s financial district',
    images: ['/images/properties/dubai4.jpg', '/images/properties/dubai4-2.jpg'],
    price: 1800,
    location: 'DIFC, Dubai',
    propertyType: 'apartment',
    bedrooms: 1,
    bathrooms: 1.5,
    guests: 2,
    amenities: ['City View', 'Art Gallery Access', 'Fine Dining', 'Concierge'],
    whatsapp: '+971501234575',
    instantBook: true,
    superhost: true,
    rating: 4.8,
    reviewCount: 112,
    coordinates: {
      latitude: 25.2048,
      longitude: 55.2708
    },
    rules: {
      smoking: false,
      pets: false,
      parties: false,
      minimumStay: 2
    },
    accessibility: ['Elevator'],
    languages: ['English', 'French'],
    cancellationPolicy: 'moderate',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: true,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  },
  {
    title: 'Family Villa in Arabian Ranches',
    description: 'Spacious family home in a prestigious golf community',
    images: ['/images/properties/dubai5.jpg', '/images/properties/dubai5-2.jpg'],
    price: 2200,
    location: 'Arabian Ranches, Dubai',
    propertyType: 'villa',
    bedrooms: 4,
    bathrooms: 4.5,
    guests: 8,
    amenities: ['Golf Course View', 'Private Garden', 'Community Pool', 'Tennis Court'],
    whatsapp: '+971501234576',
    instantBook: false,
    superhost: true,
    rating: 4.7,
    reviewCount: 85,
    coordinates: {
      latitude: 25.0508,
      longitude: 55.2242
    },
    rules: {
      smoking: false,
      pets: true,
      parties: false,
      minimumStay: 3
    },
    accessibility: ['Ground floor access'],
    languages: ['English', 'Arabic'],
    cancellationPolicy: 'moderate',
    selfCheckIn: true,
    parking: true,
    pool: true,
    airConditioning: true,
    wifi: true,
    kitchen: true,
    washer: true,
    dryer: true,
    workspace: true,
    tv: true,
    heating: false,
    securityCameras: true,
    smokeAlarm: true,
    carbonMonoxideAlarm: true,
    firstAidKit: true,
    fireExtinguisher: true,
    essentials: true
  }
];

async function seedDatabase() {
  try {
    await connectDB();
    
    // Clear existing properties
    await Property.deleteMany({});
    
    // Insert new properties
    await Property.insertMany(properties);
    
    console.log('Database seeded successfully');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase(); 